### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by AkhmadBabaev** [WisestKAA/FSD-front-2nd-tsk#10]
Компоненты которые существуют только в ui-kit страницах к примеру logo-ui-kit или colors, переименуй по принципу ui-соmponentName (пример ui-logo).

![image](https://user-images.githubusercontent.com/51095975/91566822-e19a6600-e94c-11ea-8a2b-cb7a08d91a85.png) 

А компонент logo-site можно переименовать в просто logo.

**Comment by AkhmadBabaev** [comment]
Перенеси импорт шрифтов с папки fonts в папку scss, для правила font-face можно создать sass миксин.

**Comment by AkhmadBabaev** [comment]
Добавь папку .vscode в gitgnore, а так же нужно удалить её из индекса git.

**Comment by WisestKAA** [comment]
#10 [deleted vscode](https://github.com/WisestKAA/FSD-front-2nd-tsk/commit/4d9d821467d0dae59d0a21d5c18202322b422f7b)

**Comment by AkhmadBabaev** [comment]
https://github.com/WisestKAA/FSD-front-2nd-tsk/blob/b407c86e25c5bb02fd70f471beb538f1a039def8/src/favicons/site.webmanifest#L4-L15

Нужно улучшить взаимодействие с favicons. В продакшене они попадают в папку favicons значит по дефолту из корня ничего импортироваться не будет, так что надо импортировать файлы которые не импортированы, а так же поправить ссылки на иконки, как например файла по этому пути **/android-chrome-192x192.png** в корне проекта нет.
